name = "giftpool"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-12-02"
keep_vars= True

[[ d1_databases ]]
binding = "DB"
database_name = "giftpool"
database_id = "edb6ea15-b13a-4ee2-aa4f-8ecd4399aa35"
migrations_dir = "./server/db/migrations"
